USE [master]
GO

/****** Object:  DdlTrigger [BRUTE_FORCE_LOGON_CONTROL]    Script Date: 21.05.2022 16:58:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

Create  TRIGGER [BRUTE_FORCE_LOGON_CONTROL]
ON ALL SERVER
FOR LOGON
AS BEGIN

	DECLARE @COUNT AS INT 
	SELECT @COUNT=COUNT(*) FROM AUDIT.DBO.BRUTE_FORCE_ATTACK
	WHERE COMPUTERIP=CONNECTIONPROPERTY('client_net_address')

	IF ISNULL(@COUNT,0)>0
	BEGIN
			SELECT @COUNT
			Rollback
	END

END
GO

ENABLE TRIGGER [BRUTE_FORCE_LOGON_CONTROL] ON ALL SERVER
GO


